### ISSUE TITLE
Editable Curve doesnt retain initial curve cv's when brought into HEngine. 

### ISSUE THREAD

**Issue by klamme** [sideeffects/HoudiniEngineForUnreal-v2#88] opened 2020-12-02 18:00 UTC
When I setup a curve node and mark it as editable.  HEngine does bring in the curve and lets me edit it, but it does not reflect the initial curve I set up in the HDA.  This makes it very awkward when first dropping in the HDA and working with the curve as the geometry reflects the initial curve but not the curve itself.

![hengine _V2_curve_issue](https://user-images.githubusercontent.com/10983694/100912316-26bac080-3485-11eb-9714-c98816e26713.gif)

Is it something I am doing wrong with the new HEngine?  This always worked before.

**Comment by dpernuit** [comment] 2021-01-14 22:44
Hi Kenny,

I could not reproduce that issue on a recent build of the plugin, have you tried with a recent daily build of H18.5 ?

The editable curve and its points have the proper position on first instantiation of the HDA for me.
If you still have the issue, could you send me your HDA?

**Comment by dpernuit** [comment] 2021-03-30 23:08
This has been fixed in the latest update.

**Closed as completed by dpernuit** 2021-03-30 23:08 UTC
